# Generated by Django 4.0.6 on 2023-05-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer_name',
        ),
    ]
