# Generated by Django 4.0.6 on 2023-05-08 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_remove_booking_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
