# Generated by Django 4.2 on 2023-05-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_complaint_admin_user_room_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_name',
        ),
    ]
