# Generated by Django 4.0.6 on 2023-05-14 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0008_booking_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin_user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='room_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
