# Generated by Django 4.0.6 on 2023-05-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_admin_user_alter_room_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='rooms/'),
        ),
    ]
